===== Floating Point Numbers

32 bit floating point numbers (data type float32) are transferred in binary32 format, as defined in [1], in little endian byte order:

*	The binary value is built from MSB to LSB by the following: Sign (1 bit), Exponent (8 bit), and Mantissa (23 bit).

64 bit double values (data type float64) are transferred in binary64 format, as defined in [1], in little endian byte order:

*	The binary value is built from MSB to LSB by the following: Sign (1 bit), Exponent (11 bit), and Fraction (53 bit). This binary value is transferred in little endian byte order.

*	Table 4 illustrates both the binary and the representation of the sample number f=7256.2568359375 as float32 in PDUs.

.+float32+ representation
[width="100%", cols="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1"]
|===


|Binary
|0 {set:cellbgcolor:#4db4eb}
|1 {set:cellbgcolor:#abfc92}
|0
|0
|0
|1
|0
|1
|1
|1 {set:cellbgcolor:#c40632}
|1
|0
|0
|0
|1
|0
|1
|1
|0
|0
|0
|0
|1
|0
|0
|0
|0
|0
|1
|1
|1
|0

|Hex
{set:cellbgcolor!}
8+^|45
8+^|E2
8+^|C2
8+^|0E

|
16+|MSB
16+>| LSB
|===
[width="100%", cols="1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1"]
|===

|Position
{set:cellbgcolor!}
8+^|n
8+^|n + 1
8+^|n + 2
8+^|n + 3


|DAT_input_output~Bin~
|0 {set:cellbgcolor:#c40632}
|0
|0
|0
|1
|1
|1
|0
|1
|1
|0
|0
|0
|0
|1
|0
|1  {set:cellbgcolor:#abfc92}
|1{set:cellbgcolor:#c40632}
|1
|0
|0
|0
|1
|0
|0 {set:cellbgcolor:#4db4eb}
|1 {set:cellbgcolor:#abfc92}
|0
|0
|0
|1
|0
|1

|DAT_input_output~Hex~
{set:cellbgcolor!}
8+^|0E
8+^|C2
8+^|E2
8+^|45

|===
See Appendix for further examples.
