==== Structuring
All PDUs are structured using fields. A field is defined by its name, a DCP compliant data type, and the position of the field within the PDU, given in bytes. Table 57 provides an overview of all specified PDU fields and their corresponding data types. Concrete PDUs are distinguished by their type (field: type_id). For all PDUs, the type_id is available at the beginning at position zero with a length of 1 byte.
A specific PDU does not contain all remaining fields, but only those required for the specific use, as can be seen in Table 62. The upcoming subsections give detailed information about each PDU.

---
.Field data types
[width="100%", cols="2,2", float="center", options="header"]
|===
|Field
|Data type specification

|data_id
|uint16

|denominator
|uint32

|error_code
|uint16

|exp_seq_id
|uint16

|log_category
|uint8

|log_level
|uint8

|log_max_num
|uint8

|log_mode
|uint8

|log_template_id
|uint8

|log_arg_val
|byte[]

|log_entries
|byte[]

|major_version
|uint8

|minor_version
|uint8

|numerator
|uint32

|op_mode
|uint8

|parameter_vr
|uint64

|param_id
|uint16

|payload
|byte[]

|pdu_seq_id
|uint16

|pos
|uint16

|receiver
|uint8

|resp_seq_id
|uint16

|scope
|uint8

|sender
|uint8

|slave_uuid	unsigned
|byte[16]

|source_data_type
|uint8

|source_vr
|uint64

|time
|int64

|state_id
|uint8

|steps
|uint32

|target_vr
|uint64

|transport_protocol
|uint8

|type_id
|uint8
|===
