== 1     Overview
---
Virtual system development is getting more and more important in a plenitude of industrial do-mains to reduce development times, stranded costs and time-to-market. Co-simulation is a par-ticularly promising approach for interoperable and modular development. The Functional Mock-up Interface (FMI) defines a standardized specification for the integration of simulation models, tools and solvers. However, the coupling and integration of real-time systems into simulation environ-ments (especially of distributed hardware-in-the-loop systems and simulations) still requires enormous effort.

The Distributed Co-Simulation Protocol (DCP) was developed in scope of the ACOSAR (Advanced Co-Simulation Open Systems Architecture) project. The DCP specifies a data model, a finite state machine, a set of protocol data units and a communication protocol. It is intended for the integra-tion of real-time and/or non-real-time systems. It features a master-slave principle. Furthermore, it is defined independently of the underlying transport protocol and distinguishes between native and non-native DCP specifications. With this approach, support for additional transport protocols may be added in the future. The DCP specification also includes a default integration methodology.

The DCP specification document at hand can lead to a modular, considerably more flexible, as well as shorter system development process. The DCP is suitable for application in numerous industrial domains. Furthermore, it has the potential to enable new business models.
