== 2           Properties and Guiding Ideas
---
In this section, properties are listed, and some principles are defined that guided the design of the DCP. Six central aspects drive the development: interoperability, integration, compatibility, com-munication, performance, and economy.

* Interoperability: The DCP defines a communication protocol intended for the exchange of simulation related information and data. It enables the interoperability of systems from different providers. This principle homogenizes the situation exposed when having a heter-ogeneous landscape of tools, protocols, and interfaces commonly found in today’s work environments. It further facilitates the deployment of co-simulation approaches across dif-ferent computers, sites, and companies.
* Integration: The DCP enables the integration of distributed real-time systems and/or non-real-time systems into one common co-simulation scenario.
The DCP operation follows a master-slave architecture. This type of architecture is benefi-cial because it ensures the integration of multiple DCP slaves into a common co-simulation scenario. This principle supports co-simulation of mixed systems, e.g. hardware setups and digital models. The DCP master-slave approach facilitates the addition and/or removal of single components without the need to stop any DCP slave. Consequently, one can switch between digital models and real hardware setups, and therefore accelerate the de-velopment process.
Furthermore, a default integration methodology is provided. It demonstrates the interplay of different parts of the DCP specification. Furthermore, it also demonstrates the role of components that are not part of this DCP specification.
*	Compatibility: The DCP is defined in a way such that it supports the integration of FMI based systems within DCP slaves. This applies to FMI for Model Exchange as well as FMI for Co-Simulation. The DCP state machine is designed that it matches operations defined in the state machine of the FMI. Furthermore, the DCP slave description file is aligned to the model description file of the FMI. The data types defined in the DCP slave description file may also be converted to FMI compatible data types. This principle supports FMI-based simulation models, considering the fact that FMI is one of the most common co-simulation standards today.
Whereas the FMI represents an application programming interface (API), the DCP repre-sents a communication protocol. Therefore, it becomes possible to integrate various kinds of systems. The DCP specification is suitable for a broad range of computing platforms. It may be implemented on hardware as well as in software. Typical examples are middle-ware, runtime environments, (virtualized) operating systems, electronic control units, FPGAs, and many more.
*	Communication: The DCP enables simulation data exchange by a variety of communication systems and transport protocols. The DCP specification refrains from further specification of the communication medium. This attribute underscores the underlying design principle that the choice of the communication medium must be as convenient as possible for the end-user. DCP abstracts from the most common communication systems. As of today, supported communication systems and transport protocols include UDP/IPv4, Bluetooth, USB, and CAN.
Modern system development processes require the exchange of many different data types. The DCP specification supports the transmission of data type primitives, vectors, bi-nary data, and strings. Finally, the DCP specification offers a dedicated safe-state. It may be used to provide the possibility to implement mechanisms for protection of operators and the involved hardware. The safety mechanisms themselves are not inherent to the DCP specification.
*	Performance: Distributed real-time and non-real-time co-simulation requires high per-formance of data exchange. For that reason, the exchanged simulation data at runtime does not contain any overhead data, like signal names or value references. The DCP sup-ports data exchange between slaves via the co-simulation master, as well as direct slave to slave data exchange. The DCP master is free to define either a number of short data segments, or all data at once for the exchange of simulation data. This also depends on the capabilities of the communication medium.
*	Economy: The DCP specification is intended to contribute to the following economic land-marks. First, it helps to reduce development time. This is achieved by independent design, development, and test of each individual subsystem. Therefore, the development process can be parallelized. Only the final integration happens collaboratively. Negotiations between system suppliers and integrators can be kept to a minimum.  Second, the DCP specifica-tion is independent of any computing platform, which can decrease computing costs., Third, a shortened time-to-market can be achieved by efficiently setting up and running an increased number of test cases. Due to the open manner and free availability of the DCP specification document, a vivid and active DCP community distributes the DCP specification document into different application domains. The creation of business opportunities, espe-cially for smaller companies, also emerges from this community. Finally, mutual support and exchange of experience will drive future development of the DCP.
